version = 1

test_patterns = [
  'gfi/test_*.py',
]

[[analyzers]]
  name = 'python'
  enabled = true

  [analyzers.meta]
  max_line_length = 100

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest",
    "browser"
  ]
  plugins = ["vue"]

[[transformers]]
  name = 'black'
  enabled = true

[[transformers]]
  name = 'prettier'
  enabled = true

[[analyzers]]
name = "secrets"
enabled = true
